apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: nginx-container
      protocol: TCP
      port: 80
      targetPort: 80
    - name: multitool-container
      protocol: TCP
      port: 1180
      targetPort: 1180
