apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
    - name: web-nginx
      port: 9001
      targetPort: 80
      nodePort: 30080
    - name: web-mtools
      port: 9002
      targetPort: 8080
      nodePort: 30082
  selector:
    app: my-app
