---
- name: Install required packages
  ansible.builtin.yum:
    name: git
    state: present
- name: Clone LightHouse repository
  ansible.builtin.git:
    repo: 'https://github.com/VKCOM/lighthouse.git'
    dest: '/var/www/lighthouse'
    version: master
- name: Ensure permissions on LightHouse directory
  ansible.builtin.file:
    path: '/var/www/lighthouse'
    state: directory
    mode: '0755'
- name: Install EPEL repo
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: present
- name: Deploy Nginx configuration for LightHouse
  ansible.builtin.template:
    src: nginx_lighthouse.j2
    dest: "/etc/nginx/conf.d/lighthouse.conf"
    mode: '0644'
  notify: Restart nginx service
- name: Ensure Nginx is running
  ansible.builtin.systemd:
    name: nginx
    state: started

