apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-multitool-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: busybox
          image: busybox:latest
          command: ['sh', '-c', 'while true; do echo "Текущее время: $(date)" >> /data/shared-file.txt; sleep 5; done']
          volumeMounts:
            - name: shared-data
              mountPath: /data
        - name: multitool
          image: praqma/network-multitool:latest
          volumeMounts:
            - name: shared-data
              mountPath: /data
