{
 "title": "Netology",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "количество свободной оперативной памяти",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\", job=\"nodeexporter\"} / 1024 / 1024 / 1024\r"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15; node_load1{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}\r"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}\r"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\", job=\"nodeexporter\"}\r"
    }
   ]
  },
  {
   "title": "утилизация CPU для nodeexporter (в процентах, 100-idle)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 -(avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "количество места на файловой системе",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype=\"ext4\", mountpoint=\"/\"} / 1024 / 1024 / 1024\r\n\r\n\r\n\r"
    }
   ]
  }
 ]
}